services:
  - type: web
    name: chat-api
    env: python
    plan: free # hoặc starter nếu bạn cần tài nguyên lớn hơn
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 5000
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri_here # Thay bằng URI của bạn sau
